version: "3"
services:
  web:
    hostname: ma0-tdi-php-apache
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: ma0-tdi-php-apache:1.0
    container_name: ma0-tdi-php-apache
    volumes:
      - ./.docker/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./src/:/var/www/html
    ports:
      - 7000:80
